ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

lfs:
  domain: "jtest.pivotal.io"
  rdomain: "io.pivotal.jtest"
  control_node: "{{ hostvars[groups['mon'][0]]['ansible_hostname'] }}"
  cluster_name: jack-kr-ceph
  major_version: "19"
  minor_version: "2"
  build_version: "0"
  patch_version: ""
  download_url: ""
  download: false
  base_path: /root
  admin_user: admin
  admin_passwd: changeme
  bin_type: tar
  nvme: true
  mon_host_num: "{{ groups['mon'] | length }}"
  osd_host_num: "{{ groups['osd'] | length }}"
  obs: false
  fs: false
  block:
    rbd: true
    iscsi: false
  net:
    conn: "dpdk"                     # dpdk or udp
    gateway: "192.168.1.1"
    ha1: 1
    ha2: 2
    type: "virtual"                  # or physical
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"
  backend:
    net:
      type: "virtual"                # or physical
      ipaddr0: "192.168.0.7"
      ipaddr1: "192.168.1.7"
      ipaddr2: "192.168.2.7"
  protocol:
    smb: false
    nfs:
      single: false
      ganesha: false
    rgw:
      single: false
      multi: false
  client:
    cephfs: false
    smb: false
    block:
      rbd: false
      iscsi: false
    nfs:
      single: false
      ganesha: false
    rgw:
      single: false
      multi: false
    net:
      type: "virtual"                # or physical
      cores: 1
      ipaddr0: "192.168.0.7"
      ipaddr1: "192.168.1.7"
      ipaddr2: "192.168.2.7"
  ext_storage:
    net:
      ipaddr0: "192.168.0."
      ipaddr1: "192.168.1."
      ipaddr2: "192.168.2."


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"

