ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

lfs:
  user: jomoon
  group: jomoon
  # mnt_dir: /home/jomoon/mnt/lfs
  # tools_dir: /home/jomoon/tools
  mnt_dir: /mnt/lfs
  tools_dir: /tools
  binutils_version: "2.43.1"
  gcc_version: "14.2.0"
  # glibc_version: "2.35"
  mpc_version: "1.3.1"
  mpfr_version: "4.2.1"
  gmp_version: "6.3.0"
  systemd_version: "12.2"
  kernel_version: "6.10.5"
  glibc_version: "2.40"
  m4_version: "1.4.19"
  ncurses_version: "6.5"
  bash_version: "5.2.32"
  coreutils_version: "9.5"
  diffutils_version: "3.10"
  file_version: "5.45"
  findutils_version: "4.10.0"
  gawk_version: "5.3.0"
  grep_version: "3.11"
  gzip_version: "1.13"
  make_version: "4.4.1"
  patch_version: "2.7.6"
  sed_version: "4.9"
  tar_version: "1.35"
  xz_version: "5.6.2"
  root_dev: sdb
  domain: "jtest.pivotal.io"
  net:
    gateway: "192.168.1.1"
    type: "virtual"                  # or physical
    ipaddr0: "192.168.0.12"
    ipaddr1: "192.168.1.12"
    ipaddr2: "192.168.2.12"


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"


