---
- name: Unpack Binutils
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/binutils-{{ lfs.binutils_version }}.tar.xz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


# Binutils building system relies on an shipped libtool copy to link against internal static libraries,
# but the libiberty and zlib copies shipped in the package do not use libtool.
# This inconsistency may cause produced binaries mistakenly linked against libraries from the host distro.
- name: Link against internal static libraries
  become_user: root
  shell: |
    sed '6009s/$add_dir//' -i ltmain.sh
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/binutils-{{ lfs.binutils_version }}"


- name: Create Build Directory for Bintuils
  become_user: root
  file:
    path: "{{ lfs.mnt_dir }}/sources/binutils-{{ lfs.binutils_version }}/build"
    state: directory
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"


- name: Configure the Binutils Build
  become_user: root
  shell: |
    export LFS_TGT=$(uname -m)-lfs-linux-gnu && ../configure --prefix=/usr --build=$(../config.guess) \
    --host=$LFS_TGT --disable-nls --enable-shared --enable-gprofng=no --disable-werror --enable-64-bit-bfd \
    --enable-new-dtags --enable-default-hash-style=gnu
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/binutils-{{ lfs.binutils_version }}/build"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Build Binutils
  become_user: root
  shell: |
    make -j {{ use_cores }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/binutils-{{ lfs.binutils_version }}/build"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Install Binutils
  become_user: root
  shell: |
    make -j {{ use_cores }} install
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/binutils-{{ lfs.binutils_version }}/build"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Remove the libtool archive files because they are harmful for cross compilation, and remove unnecessary static libraries
  become_user: root
  shell: |
    rm -v $LFS/usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes,sframe}.{a,la}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/binutils-{{ lfs.binutils_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"

