---
- name: Unpack Binutils
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/binutils-{{ lfs.binutils_version }}.tar.xz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


- name: Link against Internal Static Libraries
  become_user: root
  shell: |
    sed '6009s/$add_dir//' -i ltmain.sh
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/binutils-{{ lfs.binutils_version }}"


- name: Create Build Directory for Bintuils
  become_user: root
  file:
    path: "{{ lfs.mnt_dir }}/sources/binutils-{{ lfs.binutils_version }}/build"
    state: directory
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"


# export LFS_TGT=$(uname -m)-lfs-linux-gnu && \
# ../configure --prefix=/usr --build=$(../config.guess) --host=$LFS_TGT  --disable-nls \
# ../configure --prefix={{ lfs.tools_dir }} \
- name: Configure the Binutils to Build
  become_user: root
  shell: |
    export LFS_TGT=$(uname -m)-lfs-linux-gnu && \
    ../configure --prefix=/usr \
    --build=$(../config.guess) --host=$LFS_TGT  --disable-nls \
    --enable-shared --enable-gprofng=no --disable-werror --enable-64-bit-bfd \
    --enable-new-dtags --enable-default-hash-style=gnu
  register: configure_binutils
  args:
    executable: /bin/bash
    chdir: "{{ lfs.mnt_dir }}/sources/binutils-{{ lfs.binutils_version }}/build"
  environment:
    LFS: "{{ lfs.mnt_dir }}"
    PATH: "{{ lfs.mnt_dir }}/tools/bin:/bin:/usr/bin"

- debug: msg={{ configure_binutils }}


- name: Build Binutils
  become_user: root
  shell: make -j {{ use_cores }}
  register: build_binutils
  args:
    executable: /bin/bash
    chdir: "{{ lfs.mnt_dir }}/sources/binutils-{{ lfs.binutils_version }}/build"
  environment:
    LFS: "{{ lfs.mnt_dir }}"
    PATH: "{{ lfs.mnt_dir }}/tools/bin:/bin:/usr/bin"
- debug: msg={{ build_binutils }}


- name: Install Binutils
  become_user: root
  shell: make -j {{ use_cores }} DESTDIR=$LFS install
  register: install_binutils
  args:
    executable: /bin/bash
    chdir: "{{ lfs.mnt_dir }}/sources/binutils-{{ lfs.binutils_version }}/build"
  environment:
    LFS: "{{ lfs.mnt_dir }}"
    PATH: "{{ lfs.mnt_dir }}/tools/bin:/bin:/usr/bin"
- debug: msg={{ install_binutils }}


- name: Remove the Libtool Archive Files
  become_user: root
  file:
    path: "{{ lfs.mnt_dir }}/usr/lib/{{ item }}"
    state: absent
  with_items:
    - libbfd.a"
    - libbfd.la"
    - libctf.a"
    - libctf.la"
    - libctf-nobfd.a"
    - libctf-nobfd.la"
    - libopcodes.a,"
    - libopcodes.la"
    - libsframe.a"
    - libsframe.la"

