---
- name: Unpack Coreutils
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/coreutils-{{ lfs.coreutils_version }}.tar.xz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


- name: Configure Coreutils
  become_user: root
  shell: |
    export LFS_TGT=$(uname -m)-lfs-linux-gnu && ./configure --prefix=/usr --host=$LFS_TGT \
    --build=$(build-aux/config.guess) --enable-install-program=hostname \
    --enable-no-install-program=kill,uptime
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/coreutils-{{ lfs.coreutils_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Build Coreutils
  become_user: root
  shell: |
    make -j {{ use_cores }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/coreutils-{{ lfs.coreutils_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Install Coreutils
  become_user: root
  shell: |
    make -j {{ use_cores }} DESTDIR=$LFS install
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/coreutils-{{ lfs.coreutils_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


# Move programs to their final expected locations. Although this is not necessary in this temporary environment,
# we must do so because some programs hardcode executable locations
- name: Move Progreams to their final expected locations
  become_user: root
  shell: |
    mv -v $LFS/usr/bin/chroot              $LFS/usr/sbin
    mkdir -pv $LFS/usr/share/man/man8
    mv -v $LFS/usr/share/man/man1/chroot.1 $LFS/usr/share/man/man8/chroot.8
    sed -i 's/"1"/"8"/'                    $LFS/usr/share/man/man8/chroot.8
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/coreutils-{{ lfs.coreutils_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"

