---
- name: Unpack Gawk
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/gawk-{{ lfs.gawk_version }}.tar.xz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


- name: Ensure Some Unneeded Files Are Not Installed
  become_user: root
  shell: |
    sed -i 's/extras//' Makefile.in
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/gawk-{{ lfs.gawk_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Configure Gawk
  become_user: root
  shell: |
    export LFS_TGT=$(uname -m)-lfs-linux-gnu && ./configure --prefix=/usr \
    --host=$LFS_TGT --build=$(build-aux/config.guess)
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/gawk-{{ lfs.gawk_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Build Gawk
  become_user: root
  shell: |
    make -j {{ use_cores }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/gawk-{{ lfs.gawk_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Install Gawk
  become_user: root
  shell: |
    make -j {{ use_cores }} DESTDIR=$LFS install
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/gawk-{{ lfs.gawk_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"

