---
- name: Unpack Grep
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/grep-{{ lfs.grep_version }}.tar.xz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


- name: Configure Grep
  become_user: root
  shell: |
    export LFS_TGT=$(uname -m)-lfs-linux-gnu && ./configure --prefix=/usr \
    --host=$LFS_TGT --build=$(./build-aux/config.guess)
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/grep-{{ lfs.grep_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Build Grep
  become_user: root
  shell: |
    make -j {{ use_cores }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/grep-{{ lfs.grep_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Install Grep
  become_user: root
  shell: |
    make -j {{ use_cores }} DESTDIR=$LFS install
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/grep-{{ lfs.grep_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"

