---
- name: Download the Sources List
  become_user: root
  get_url:
    url: https://libisl.sourceforge.io/isl-{{ lfs.isl_version }}.tar.xz
    dest: "{{ lfs.mnt_dir }}/sources/isl-{{ lfs.isl_version }}.tar.xz"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"


- name: Unpack Libisl
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/isl-{{ lfs.isl_version }}.tar.xz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


- name: Configure Libisl
  become_user: root
  shell: |
    ./configure --prefix=$LFS/usr \
    --disable-static \
    --docdir=$LFS/usr/share/doc/isl-{{ lfs.isl_version }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/isl-{{ lfs.isl_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Build Libisl
  become_user: root
  shell: |
    make -j {{ use_cores }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/isl-{{ lfs.isl_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Install Libisl
  become_user: root
  shell: |
    make -j 8 install
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/isl-{{ lfs.isl_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Place Libisl
  become_user: root
  shell: |
    install -m644 doc/{CodingStyle,manual.pdf,SubmittingPatches,user.pod} $LFS/usr/share/doc/isl-0.27
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/isl-{{ lfs.isl_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Place Libisl
  become_user: root
  file: 
    path: "{{ lfs.mnt_dir }}/usr/share/gdb/auto-load/usr/lib"
    state: directory
    owner: root
    group: root
    mode: 0755


- name: Copy Libisl Python Libary
  become_user: root
  shell: |
    mv -v $LFS/usr/lib/libisl*gdb.py $LFS/usr/share/gdb/auto-load/usr/lib
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/isl-{{ lfs.isl_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"

