---
- name: Unpack Bash
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/bash-{{ lfs.bash_version }}.tar.xz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


- name: Configure Bash
  become_user: root
  shell: |
    export LFS_TGT=$(uname -m)-lfs-linux-gnu && ./configure --prefix=/usr --build=$(sh support/config.guess) \
    --host=$LFS_TGT --without-bash-malloc bash_cv_strtold_broken=no
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/m4-{{ lfs.bash_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Build Bash
  become_user: root
  shell: |
    make -j {{ use_cores }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/m4-{{ lfs.bash_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Install Bash
  become_user: root
  shell: |
    make -j {{ use_cores }} DESTDIR=$LFS install
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/m4-{{ lfs.bash_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Link Bash
  become_user: root
  shell: |
    ln -sv bash $LFS/bin/sh
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/m4-{{ lfs.bash_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"

