---
- name: Unpack Textinfo
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/textinfo-{{ pkgs.textinfo_ver }}.tar.gz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


- name: Prepare Textinfo for compilation
  become_user: root
  shell: |
    ./configure --prefix=/usr
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/textinfo-{{ pkgs.textinfo_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Compile the package
  become_user: root
  shell: |
    make -j {{ use_cores }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/textinfo-{{ pkgs.textinfo_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Install the package
  become_user: root
  shell: |
    make -j {{ use_cores }} install
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/textinfo-{{ pkgs.textinfo_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


