# 7.7. Gettext-0.22.5
# The Gettext package contains utilities for internationalization and localization. These allow programs to be compiled with NLS (Native Language Support), enabling them to output messages in the user's native language.
#
#Approximate build time:
#1.1 SBU
#Required disk space:
#321 MB
#7.7.1. Installation of Gettext
#For our temporary set of tools, we only need to install three programs from Gettext.
#
#Prepare Gettext for compilation:
#
#./configure --disable-shared
#The meaning of the configure option:
#
#--disable-shared
#We do not need to install any of the shared Gettext libraries at this time, therefore there is no need to build them.
#
#Compile the package:
#
#make
#Install the msgfmt, msgmerge, and xgettext programs:
#
#cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin
#Details on this package are located in Section 8.33.2, “Contents of Gettext.”
---

- name: Unpack Gettext
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/gettext-{{ pkgs.gettext_ver }}.tar.gz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


- name: Prepare Gettext for compilation
  become_user: root
  shell: |
    ./configure --disable-shared
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/gettext-{{ pkgs.gettext_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Compile the package
  become_user: root
  shell: |
    make -j {{ use_cores }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/gettext-{{ pkgs.gettext_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Install the msgfmt, msgmerge, and xgettext programs
  become_user: root
  shell: |
    cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/gettext-{{ pkgs.gettext_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"

