---
- name: Unpack Python
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/python-{{ pkgs.python_ver }}.tar.gz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


- name: Prepare Python for compilation
  become_user: root
  shell: |
    ./configure --prefix=/usr --enable-shared --without-ensurepip
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/python-{{ pkgs.python_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Compile the package
  become_user: root
  shell: |
    make -j {{ use_cores }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/python-{{ pkgs.python_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Install the package
  become_user: root
  shell: |
    make -j {{ use_cores }} install
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/python-{{ pkgs.python_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"

