# The FHS recommends using the /var/lib/hwclock directory instead of the usual /etc directory as the location for the adjtime file. Create this directory with:
- name: Create this /var/lib/hwclock directory for FHS
  become_user: root
  shell: |
    mkdir -pv /var/lib/hwclock
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/textinfo-{{ pkgs.textinfo_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Unpack Util-linux
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/util-linux-{{ pkgs.util_linux_ver }}.tar.gz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


- name: Prepare Util-linux for compilation
  become_user: root
  shell: |
    ./configure --libdir=/usr/lib     \
            --runstatedir=/run    \
            --disable-chfn-chsh   \
            --disable-login       \
            --disable-nologin     \
            --disable-su          \
            --disable-setpriv     \
            --disable-runuser     \
            --disable-pylibmount  \
            --disable-static      \
            --disable-liblastlog2 \
            --without-python      \
            ADJTIME_PATH=/var/lib/hwclock/adjtime \
            --docdir=/usr/share/doc/util-linux-{{ pkgs.util_linux_ver }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/util-linux-{{ pkgs.util_linux_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Compile the package
  become_user: root
  shell: |
    make -j {{ use_cores }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/util-linux-{{ pkgs.util_linux_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Install the package
  become_user: root
  shell: |
    make -j {{ use_cores }} install
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/textinfo-{{ pkgs.textinfo_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


