# 7.7. Gettext-0.22.5
# The Gettext package contains utilities for internationalization and localization. These allow programs to be compiled with NLS (Native Language Support), enabling them to output messages in the user's native language.
#
#Approximate build time:
#1.1 SBU
#Required disk space:
#321 MB
#7.7.1. Installation of Gettext
#For our temporary set of tools, we only need to install three programs from Gettext.
#
#Prepare Gettext for compilation:
#
#./configure --disable-shared
#The meaning of the configure option:
#
#--disable-shared
#We do not need to install any of the shared Gettext libraries at this time, therefore there is no need to build them.
#
#Compile the package:
#
#make
#Install the msgfmt, msgmerge, and xgettext programs:
#
#cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin
#Details on this package are located in Section 8.33.2, “Contents of Gettext.”
