---
- name: Unpack Perl
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/perl-{{ pkgs.perl_ver }}.tar.gz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


- name: Prepare Perl for compilation
  become_user: root
  shell: |
    sh Configure -des                                        \
             -D prefix=/usr                                  \
             -D vendorprefix=/usr                            \
             -D useshrplib                                   \
             -D privlib=/usr/lib/perl5/5.40/core_perl        \
             -D archlib=/usr/lib/perl5/5.40/core_perl        \
             -D sitelib=/usr/lib/perl5/5.40/site_perl        \
             -D sitearch=/usr/lib/perl5/5.40/site_perl       \
             -D vendorlib=/usr/lib/perl5/5.40/vendor_perl    \
             -D vendorarch=/usr/lib/perl5/5.40/vendor_perl
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/perl-{{ pkgs.perl_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Compile the package
  become_user: root
  shell: |
    make -j {{ use_cores }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/perl-{{ pkgs.perl_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Install the package
  become_user: root
  shell: |
    make -j {{ use_cores }} install
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/perl-{{ pkgs.perl_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"

