
# First, remove the currently installed documentation files to prevent them from ending up in the final system, and to save about 35 MB:
- name: Remove the currently installed documentation files to prevent them from ending up in the final system, and to save about 35 MB
  become_user: root
  shell: |
    rm -rf /usr/share/{info,man,doc}/*
  args:
    chdir: "{{ lfs.mnt_dir }}/"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


#Second, on a modern Linux system, the libtool .la files are only useful for libltdl. No libraries in LFS are loaded by libltdl, and it's known that some .la files can cause BLFS package failures. Remove those files now:
- name: Remove those files now
  become_user: root
  shell: |
    find /usr/{lib,libexec} -name \*.la -delete
  args:
    chdir: "{{ lfs.mnt_dir }}/"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


# The current system size is now about 3 GB, however the /tools directory is no longer needed. It uses about 1 GB of disk space. Delete it now:
- name: Delete it now
  become_user: root
  shell: |
    rm -rf /tools
  args:
    chdir: "{{ lfs.mnt_dir }}/"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: unmount the virtual file systems before making a backup
  become_user: root
  shell: |
    mountpoint -q $LFS/dev/shm && umount $LFS/dev/shm
    umount $LFS/dev/pts
    umount $LFS/{sys,proc,run,dev}
  args:
    chdir: "{{ lfs.mnt_dir }}/"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


# Make sure you have at least 1 GB free disk space (the source tarballs will be included in the backup archive) on the file system containing the directory where you create the backup archive.
# Note that the instructions below specify the home directory of the host system's root user, which is typically found on the root file system. Replace $HOME by a directory of your choice if you do not want to have the backup stored in root's home directory.
# Create the backup archive by running the following command:
#
# [Note] Note
# Because the backup archive is compressed, it takes a relatively long time (over 10 minutes) even on a reasonably fast system.

- name: Create the backup archive
  become_user: root
  shell: |
    cd $LFS
    tar -cJpf $HOME/lfs-temp-tools-12.2-systemd.tar.xz .
  args:
    chdir: "{{ lfs.mnt_dir }}/"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Use this backup to restore the system and save some recovery time
  become_user: root
  shell: |
    cd $LFS
    rm -rf ./*
    tar -xpf $HOME/lfs-temp-tools-12.2-systemd.tar.xz
  args:
    chdir: "{{ lfs.mnt_dir }}/"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


