---
- name: Unpack Xz
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/xz-{{ lfs.xz_version }}.tar.xz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


- name: Configure Xz
  become_user: root
  shell: |
    export LFS_TGT=$(uname -m)-lfs-linux-gnu && ./configure --prefix=/usr  \
    --host=$LFS_TGT --build=$(build-aux/config.guess) \
    --disable-static \
    --docdir=/usr/share/doc/xz-5.6.2
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/xz-{{ lfs.xz_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Build Xz
  become_user: root
  shell: |
    make -j {{ use_cores }}
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/xz-{{ lfs.xz_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Install Xz
  become_user: root
  shell: |
    make -j {{ use_cores }} DESTDIR=$LFS install
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/xz-{{ lfs.xz_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Remove the libtool archive file because it is harmful for cross compilation
  become_user: root
  shell: |
    rm -v $LFS/usr/lib/liblzma.la
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/xz-{{ lfs.xz_version }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"

