---
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for Package Versions
  import_tasks: set-lfs-facts.yml
  tags:
    - build
    - prepare
    - partition
    - download
    - env
    - binutils
    - gcc


- name: Prepare the Host System
  import_tasks: host-prep.yml
  tags:
    - prepare
    - build


- name: Partition the disk for LFS
  import_tasks: partition.yml
  tags:
    - partition
    - build


- name: Download the LFS Sources Files
  import_tasks: download-sources.yml
  tags:
    - download
    - build


- name: Perform the Final Preparations
  import_tasks: final-prep.yml
  tags:
    - env
    - build


- name: Build Binutils ( stage 1 )
  import_tasks: tools/binutils-stage1.yml
  tags:
    - binutils
    - build


- name: Build GCC ( Stage 1 )
  import_tasks: tools/gcc-stage1.yml
  tags:
    - gcc
    - build


- name: Build Linux Kernel Header
  import_tasks: tools/linux-headers.yml
  tags:
    - headers
    - build


- name: Build GLIBC ( Stage )
  import_tasks: tools/glibc-stage.yml
  tags:
    - glibc
    - build


- name: Build Libstdc++ ( Stage )
  import_tasks: tools/libstdc-stage.yml
  tags:
    - libstdc
    - build


