8.71.1. Installation of Tar
Prepare Tar for compilation:

FORCE_UNSAFE_CONFIGURE=1  \
./configure --prefix=/usr
The meaning of the configure option:

FORCE_UNSAFE_CONFIGURE=1
This forces the test for mknod to be run as root. It is generally considered dangerous to run this test as the root user, but as it is being run on a system that has only been partially built, overriding it is OK.

Compile the package:

make
To test the results, issue:

make check
One test, capabilities: binary store/restore, is known to fail if it is run because LFS lacks selinux, but will be skipped if the host kernel does not support extended attributes or security labels on the filesystem used for building LFS.

Install the package:

make install
make -C doc install-html docdir=/usr/share/doc/tar-1.35
8.71.2. Contents of Tar
Installed programs:
tar
Installed directory:
/usr/share/doc/tar-1.35
Short Descriptions
tar

Creates, extracts files from, and lists the contents of archives, also known as tarballs

