8.61.1. Installation of Gawk
First, ensure some unneeded files are not installed:

sed -i 's/extras//' Makefile.in
Prepare Gawk for compilation:

./configure --prefix=/usr
Compile the package:

make
To test the results, issue:

chown -R tester .
su tester -c "PATH=$PATH make check"
Install the package:

rm -f /usr/bin/gawk-5.3.0
make install
The meaning of the command:

rm -f /usr/bin/gawk-5.3.0
The building system will not recreate the hard link gawk-5.3.0 if it already exists. Remove it to ensure that the previous hard link installed in Section 6.9, “Gawk-5.3.0” is updated here.

The installation process already created awk as a symlink to gawk, create its man page as a symlink as well:

ln -sv gawk.1 /usr/share/man/man1/awk.1
If desired, install the documentation:

mkdir -pv                                   /usr/share/doc/gawk-5.3.0
cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk-5.3.0
8.61.2. Contents of Gawk
Installed programs:
awk (link to gawk), gawk, and gawk-5.3.0
Installed libraries:
filefuncs.so, fnmatch.so, fork.so, inplace.so, intdiv.so, ordchr.so, readdir.so, readfile.so, revoutput.so, revtwoway.so, rwarray.so, and time.so (all in /usr/lib/gawk)
Installed directories:
/usr/lib/gawk, /usr/libexec/awk, /usr/share/awk, and /usr/share/doc/gawk-5.3.0
Short Descriptions
awk

A link to gawk

gawk

A program for manipulating text files; it is the GNU implementation of awk

gawk-5.3.0

A hard link to gawk

