8.60.1. Installation of Diffutils
Prepare Diffutils for compilation:

./configure --prefix=/usr
Compile the package:

make
To test the results, issue:

make check
Install the package:

make install
8.60.2. Contents of Diffutils
Installed programs:
cmp, diff, diff3, and sdiff
Short Descriptions
cmp

Compares two files and reports any differences byte by byte

diff

Compares two files or directories and reports which lines in the files differ

diff3

Compares three files line by line

sdiff

Merges two files and interactively outputs the results

