8.18.1. Installation of DejaGNU
The upstream recommends building DejaGNU in a dedicated build directory:

mkdir -v build
cd       build
Prepare DejaGNU for compilation:

../configure --prefix=/usr
makeinfo --html --no-split -o doc/dejagnu.html ../doc/dejagnu.texi
makeinfo --plaintext       -o doc/dejagnu.txt  ../doc/dejagnu.texi
To test the results, issue:

make check
Install the package:

make install
install -v -dm755  /usr/share/doc/dejagnu-1.6.3
install -v -m644   doc/dejagnu.{html,txt} /usr/share/doc/dejagnu-1.6.3
8.18.2. Contents of DejaGNU
Installed program:
dejagnu and runtest
Short Descriptions
dejagnu

DejaGNU auxiliary command launcher

runtest

A wrapper script that locates the proper expect shell and then runs DejaGNU
