8.66.1. Installation of IPRoute2
The arpd program included in this package will not be built since it depends on Berkeley DB, which is not installed in LFS. However, a directory and a man page for arpd will still be installed. Prevent this by running the commands shown below.

sed -i /ARPD/d Makefile
rm -fv man/man8/arpd.8
Compile the package:

make NETNS_RUN_DIR=/run/netns
This package does not have a working test suite.

Install the package:

make SBINDIR=/usr/sbin install
If desired, install the documentation:

mkdir -pv             /usr/share/doc/iproute2-6.10.0
cp -v COPYING README* /usr/share/doc/iproute2-6.10.0
8.66.2. Contents of IPRoute2
Installed programs:
bridge, ctstat (link to lnstat), genl, ifstat, ip, lnstat, nstat, routel, rtacct, rtmon, rtpr, rtstat (link to lnstat), ss, and tc
Installed directories:
/etc/iproute2, /usr/lib/tc, and /usr/share/doc/iproute2-6.10.0
Short Descriptions
bridge

Configures network bridges

ctstat

Connection status utility

genl

Generic netlink utility front end

ifstat

Shows interface statistics, including the number of packets transmitted and received, by interface

ip

The main executable. It has several different functions, including these:

ip link <device> allows users to look at the state of devices and to make changes

ip addr allows users to look at addresses and their properties, add new addresses, and delete old ones

ip neighbor allows users to look at neighbor bindings and their properties, add new neighbor entries, and delete old ones

ip rule allows users to look at the routing policies and change them

ip route allows users to look at the routing table and change routing table rules

ip tunnel allows users to look at the IP tunnels and their properties, and change them

ip maddr allows users to look at the multicast addresses and their properties, and change them

ip mroute allows users to set, change, or delete the multicast routing

ip monitor allows users to continuously monitor the state of devices, addresses and routes

lnstat

Provides Linux network statistics; it is a generalized and more feature-complete replacement for the old rtstat program

nstat

Displays network statistics

routel

A component of ip route, for listing the routing tables

rtacct

Displays the contents of /proc/net/rt_acct

rtmon

Route monitoring utility

rtpr

Converts the output of ip -o into a readable form

rtstat

Route status utility

ss

Similar to the netstat command; shows active connections

tc

Traffic control for Quality of Service (QoS) and Class of Service (CoS) implementations

tc qdisc allows users to set up the queueing discipline

tc class allows users to set up classes based on the queuing discipline scheduling

tc filter allows users to set up the QoS/CoS packet filtering

tc monitor can be used to view changes made to Traffic Control in the kernel.

