Prepare GDBM for compilation:

./configure --prefix=/usr    \
            --disable-static \
            --enable-libgdbm-compat
The meaning of the configure option:

--enable-libgdbm-compat
This switch enables building the libgdbm compatibility library. Some packages outside of LFS may require the older DBM routines it provides.

Compile the package:

make
To test the results, issue:

make check
Install the package:

make install
8.38.2. Contents of GDBM
Installed programs:
gdbm_dump, gdbm_load, and gdbmtool
Installed libraries:
libgdbm.so and libgdbm_compat.so
Short Descriptions
gdbm_dump

Dumps a GDBM database to a file

gdbm_load

Recreates a GDBM database from a dump file

gdbmtool

Tests and modifies a GDBM database

libgdbm

Contains functions to manipulate a hashed database

libgdbm_compat

Compatibility library containing older DBM functions

