---
- name: Unpack Man-pages
  become_user: root
  unarchive:
    src: "{{ lfs.mnt_dir }}/sources/man-pages-{{ pkgs.man_pages_ver }}.tar.xz"
    dest: "{{ lfs.mnt_dir }}/sources"
    owner: "{{ lfs.user }}"
    group: "{{ lfs.group }}"
    remote_src: yes


# Libxcrypt will provide a better version of these man pages
- name: Remove two man pages for password hashing functions
  become_user: root
  shell: |
    cp services protocols /etc
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/man-pages-{{ pkgs.man_pages_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"


- name: Install Man-pages by running
  become_user: root
  shell: |
    make prefix=/usr install
  args:
    chdir: "{{ lfs.mnt_dir }}/sources/man-pages-{{ pkgs.man_pages_ver }}"
  environment:
    LFS: "{{ lfs.mnt_dir }}"

