---
- name: Update Everything
  apt:
    upgrade: dist
    update_cache: yes
    autoclean: yes
    autoremove: yes


- name: Install LFS Dependencies
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages: "{{ install_pkgs }}"


- name: Disable Ubuntu's Use of Dash as the Default Shell Instead of Bash
  debconf:
    name: dash
    question: dash/sh
    vtype: boolean
    value: false


- name: Reconfigure Dash With the New Setting
  command: /sbin/dpkg-reconfigure dash -p critical


- name: Disable Ubuntu's Annoying Habit of Automounting Newly Formatted Disks
  command: gsettings set org.gnome.desktop.media-handling automount false


- name: Copy Version Check Scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ lfs.mnt_dir }}/{{ item }}"
    mode: 0755
  register: copy_version_check_scripts
  with_items:
    - "version-check.sh"
- debug: msg={{ copy_version_check_scripts }}


- name: Create the LFS User's Dotfiles
  shell: |
    ./version-check.sh
  register: version_check
  args:
    executable: /bin/bash
    chdir: "{{ lfs.mnt_dir }}/"
  failed_when: >
    version_check.rc != 0 or
    'ERROR' in version_check.stdout or
    'not found' in version_check.stdout or
    'failed' in version_check.stdout

