---
- name: Create a New MBR Label on the Disk, Along with the Boot Partition
  parted:
    device: "/dev/{{ lfs.root_dev }}"
    label: msdos
    state: present
    number: 1
    part_end: 100MiB
    unit: 'KiB'
  register: part_info
- debug:
    var: part_info


- name: Create the Root Partition
  parted:
    device: "/dev/{{ lfs.root_dev }}"
    state: present
    number: 2
    part_start: "{{ part_info.partitions.0.end }}KiB"
    part_end: 100%


- name: Format the Boot Partition
  filesystem:
    dev: "/dev/{{ lfs.root_dev }}1"
    fstype: ext4


- name: Format the Root Partition
  filesystem:
    dev: "/dev/{{ lfs.root_dev }}2"
    fstype: ext4


- name: Mount the Root Partition
  mount:
    path: "{{ lfs.mnt_dir }}"
    src: "/dev/{{ lfs.root_dev }}2"
    fstype: ext4
    state: mounted


- name: Mount the Boot Partition
  mount:
    path: "{{ lfs.mnt_dir }}/boot"
    src: "/dev/{{ lfs.root_dev }}1"
    fstype: ext4
    state: mounted

